[custom]

;规则集定义
ruleset=⚡ isDIRECT,https://raw.githubusercontent.com/GGBondLee/openclash/refs/heads/main/isDIRECT.list
ruleset=✈️ isProxy,https://raw.githubusercontent.com/GGBondLee/openclash/refs/heads/main/isProxy.list
ruleset=💬 Instagram,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Instagram.list
ruleset=📲 Telegram,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list
ruleset=🎵 TikTok,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.list
ruleset=🐤 Twitter,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Twitter.list
ruleset=🤖 AI,https://raw.githubusercontent.com/GGBondLee/openclash/refs/heads/main/AI.list
ruleset=👨🏿‍💻 GitHub,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.list
ruleset=👨🏿‍💻 GitHub,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.yaml
ruleset=📹 YouTube,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=🍀 Google,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.list
ruleset=🚀 国外连接,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=🐟 漏网之鱼,[]FINAL



;策略组定义
custom_proxy_group=⚡ isDIRECT`select`[]DIRECT`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]📌 台湾节点
custom_proxy_group=✈️ isProxy`select`[]🚀 国外连接`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]📌 台湾节点
custom_proxy_group=🤖 AI`select`[]🚀 国外连接`[]🇺🇲 美国节点`[]📌 台湾节点`[]🇭🇰 香港节点
custom_proxy_group=🎵 TikTok`select`[]🚀 国外连接`[]🇺🇲 美国节点`[]🇯🇵 日本节点`[]📌 台湾节点
custom_proxy_group=🐤 Twitter`select`[]🚀 国外连接`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]📌 台湾节点
custom_proxy_group=📲 Telegram`select`[]🚀 国外连接`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]📌 台湾节点
custom_proxy_group=💬 Instagram`select`[]🚀 国外连接`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]📌 台湾节点
custom_proxy_group=📹 YouTube`select`[]🚀 国外连接`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]📌 台湾节点
custom_proxy_group=🍀 Google`select`[]DIRECT`[]🚀 国外连接`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]📌 台湾节点
custom_proxy_group=👨🏿‍💻 GitHub`select`[]DIRECT`[]🚀 国外连接`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]📌 台湾节点
custom_proxy_group=🚀 国外连接`select`[]DIRECT`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]📌 台湾节点
custom_proxy_group=🐟 漏网之鱼`select`[]DIRECT`[]🚀 国外连接`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]📌 台湾节点`[]🇯🇵 日本节点


custom_proxy_group=🚀 国外连接`select`(美|台湾|香港|日本|新)
custom_proxy_group=📌 台湾节点`select`(?=.*(台湾))^((?!(深港|US|家宽|游戏|剩余|流量)).)*$
custom_proxy_group=🇺🇲 美国节点`select`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)
custom_proxy_group=🇭🇰 香港节点`select`(?=.*(香港|HK|Hong Kong|🇭🇰|HongKong))^((?!(深港|US|家宽|游戏|剩余|流量)).)*$
custom_proxy_group=🇯🇵 日本节点`select`(?=.*(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan))^((?!(家宽|游戏|剩余|流量)).)*$


;启用自定义规则集

enable_rule_generator=true
overwrite_original_rules=true
